---
before:
  hooks:
  - 'go mod download'

builds:
- main: './main.go'
  env:
  - 'CGO_ENABLED=0'
  goos:
  - 'windows'
  - 'linux'
  - 'darwin'
  goarch:
  - 'amd64'
  ldflags:
  - '-s'
  - '-w'
  - '-X main.version={{.Version}}'
  - '-X main.buildHash={{.Commit}}'
  - '-X main.buildDate={{.Date}}'

archives:
- replacements:
    darwin: 'Darwin'
    linux: 'Linux'
    windows: 'Windows'
    amd64: 'x86_64'
  format: 'tar.gz'
  format_overrides:
  - goos: 'windows'
    format: 'zip'
  files:
      - 'LICENSE'
      - 'README.md'

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: 'asc'
  filters:
    exclude:
    - '^docs:'
    - '^test:'
...
