---
name: 'release-on-tag'

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout source'
        uses: 'actions/checkout@v2'
        with:
          fetch-depth: 0

      - name: 'setup go'
        uses: 'actions/setup-go@v2'
        with:
          go-version: '1.17.9'

      - name: 'release'
        uses: 'goreleaser/goreleaser-action@v2'
        with:
          args: 'release --rm-dist'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
...
